<a href="https://colab.research.google.com/github/ManantenaKiady/Pytorch-fundamentals/blob/master/Notebooks/Pytorch_building_blocks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What you will learn

In this notebook, we will explore the building blocks of Pytorch ( Deep Learning)

- Tensors
- Learning Algorithms (Backpropagation)
  - Forward and Backward Pass
  - Auto-Grad
- Datasets
  - DataLoader
- Optimizers

# Setup

In [2]:
!pip3 install torch torchvision torchaudio

# Check the installed version 
import torch
torch.__version__


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


'1.13.0+cu116'

Configure

In [11]:
# Check if GPU are available and set the device to use it
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

Using cuda device


## 1- Tensors

Tensors are a specialized data structure that are very similar to arrays and matrices. (Multidimentional Arrays)
 
*Source: https://pytorch.org/tutorials/*

eg of tensors: 

`scalar: 1`

`vector: [1, 2, 3]`

`matrices: [[1,2,3][4,5,6]]`

In [4]:
import torch

### Initialize Tensors with `torch`

**From Python list**

In [5]:
# List of list in Python 
m = [[1,2,3],[4,5,6]]
# Creating a tensor from list of list
M = torch.tensor(m)

print(f"Type of m: {type(m)}")
print(f"Type of M: {type(M)}")

Type of m: <class 'list'>
Type of M: <class 'torch.Tensor'>


**From Arrays (Numpy)**

What is numpy, who knows ?

Source: https://numpy.org/

In [16]:
import numpy as np 

# Convert m into numpy array
arr = np.array(m)
print(f"Type of arr: {type(arr)}")
# Transform arr into tensor
ts_arr = torch.tensor(arr)
print(f"Type of ts_arr: {type(ts_arr)}")

Type of arr: <class 'numpy.ndarray'>
Type of ts_arr: <class 'torch.Tensor'>


From another Tensor ?

**Tensor Attributes**

shape, dtype, device

<font color="green"> Q1: Create a tensor from a python list and print all attributes ? </font>

To make a tensor use of a specific device, we can use the `to(device)` method.

In [8]:
ts_arr.device

device(type='cpu')

In [23]:
ts_arr = ts_arr.to(device)
print(f"Tensor ts_arr is stored on: {ts_arr.device}")

Tensor ts_arr is stored on: cuda:0


**Operations with Tensors**

Indexing, Slicing, Sampling, math Operations, etc More [here](https://pytorch.org/docs/stable/torch.html)

Indexing

In [39]:
# Indexing

ts_rand = torch.rand(4,4)
print(f"Tensor rand = {ts_rand}")
print()
# All rows of column 1
print(f"ts_rand[:,1] = {ts_rand[:,1]}")

Tensor rand = tensor([[0.6814, 0.8698, 0.5616, 0.5257],
        [0.6909, 0.4972, 0.5945, 0.3721],
        [0.8997, 0.2054, 0.2658, 0.2162],
        [0.7809, 0.0977, 0.2236, 0.5856]])

ts_rand[:,1] = tensor([0.8698, 0.4972, 0.2054, 0.0977])


Concatenate or join

In [38]:
# Concatenate or join
# Along the column
ts_ccat = torch.cat([ts_rand, torch.ones(4,4)], dim=1)
print(ts_ccat)

tensor([[0.7307, 0.6157, 0.0402, 0.3175, 1.0000, 1.0000, 1.0000, 1.0000],
        [0.9854, 0.1632, 0.6838, 0.6638, 1.0000, 1.0000, 1.0000, 1.0000],
        [0.4109, 0.7447, 0.3307, 0.9590, 1.0000, 1.0000, 1.0000, 1.0000],
        [0.0447, 0.8286, 0.5595, 0.9830, 1.0000, 1.0000, 1.0000, 1.0000]])


 Math operations

<font color='green'> Q2: Using multiplication operators with tensors ? </font>

In [76]:
ts_res = ts_rand * ts_ccat
# What going on ?

RuntimeError: ignored

In [80]:
ts_rand.matmul(ts_ccat)

tensor([[1.6092, 1.4153, 1.1021, 1.8491, 2.6385, 2.6385, 2.6385, 2.6385],
        [1.2556, 1.2576, 0.7726, 1.4853, 2.1547, 2.1547, 2.1547, 2.1547],
        [0.9787, 0.9645, 0.3855, 0.8894, 1.5871, 1.5871, 1.5871, 1.5871],
        [0.7849, 1.1485, 0.4998, 1.1028, 1.6878, 1.6878, 1.6878, 1.6878]])

Inplace operations

In [84]:
ts_ccat.add_(5)

tensor([[5.7307, 5.6157, 5.0402, 5.3175, 6.0000, 6.0000, 6.0000, 6.0000],
        [5.9854, 5.1632, 5.6838, 5.6638, 6.0000, 6.0000, 6.0000, 6.0000],
        [5.4109, 5.7447, 5.3307, 5.9590, 6.0000, 6.0000, 6.0000, 6.0000],
        [5.0447, 5.8286, 5.5595, 5.9830, 6.0000, 6.0000, 6.0000, 6.0000]])

In [85]:
ts_ccat

tensor([[5.7307, 5.6157, 5.0402, 5.3175, 6.0000, 6.0000, 6.0000, 6.0000],
        [5.9854, 5.1632, 5.6838, 5.6638, 6.0000, 6.0000, 6.0000, 6.0000],
        [5.4109, 5.7447, 5.3307, 5.9590, 6.0000, 6.0000, 6.0000, 6.0000],
        [5.0447, 5.8286, 5.5595, 5.9830, 6.0000, 6.0000, 6.0000, 6.0000]])