<a href="https://colab.research.google.com/github/ManantenaKiady/Pytorch-fundamentals/blob/master/Notebooks/Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What we will cover

In this notebook, we will explore the building blocks of Pytorch ( Deep Learning)

- Tensors
- Learning Algorithms (Backpropagation)
  - Forward and Backward Pass
  - Auto-Grad
  - Optimizers
- Datasets
  - DataLoader

## Setup

In [ ]:
!pip3 install torch torchvision torchaudio

# Check the installed version 
import torch
torch.__version__


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


'1.13.0+cu116'

Configure

In [ ]:
# Check if GPU are available and set the device to use it
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

Using cuda device


## 1- Tensors

Tensors are a specialized data structure that are very similar to arrays and matrices. (Multidimentional Arrays)
 
*Source: https://pytorch.org/tutorials/*

eg of tensors: 

`scalar: 1`

`vector: [1, 2, 3]`

`matrices: [[1,2,3][4,5,6]]`

In [ ]:
import torch

### Initialize Tensors with `torch`

**From Python list**

In [ ]:
# List of list in Python 
m = [[1,2,3],[4,5,6]]
# Creating a tensor from list of list
M = torch.tensor(m)

print(f"Type of m: {type(m)}")
print(f"Type of M: {type(M)}")

Type of m: <class 'list'>
Type of M: <class 'torch.Tensor'>


**From Arrays (Numpy)**

What is numpy, who knows ?

Source: https://numpy.org/

In [ ]:
import numpy as np 

# Convert m into numpy array
arr = np.array(m)
print(f"Type of arr: {type(arr)}")
# Transform arr into tensor
ts_arr = torch.tensor(arr)
print(f"Type of ts_arr: {type(ts_arr)}")

Type of arr: <class 'numpy.ndarray'>
Type of ts_arr: <class 'torch.Tensor'>


From another Tensor ?

**Tensor Attributes**

shape, dtype, device

<font color="green"> Q1: Create a tensor from a python list and print all attributes ? </font>

In [ ]:
# ------- Write your answer here --------

To make a tensor use of a specific device, we can use the `to(device)` method.

In [ ]:
ts_arr.device

device(type='cpu')

In [ ]:
ts_arr = ts_arr.to(device)
print(f"Tensor ts_arr is stored on: {ts_arr.device}")

Tensor ts_arr is stored on: cuda:0


**Operations with Tensors**

Indexing, Slicing, Sampling, math Operations, etc More [here](https://pytorch.org/docs/stable/torch.html)

Indexing

In [ ]:
# Indexing

ts_rand = torch.rand(4,4)
print(f"Tensor rand = {ts_rand}")
print()
# All rows of column 1
print(f"ts_rand[:,1] = {ts_rand[:,1]}")

Tensor rand = tensor([[0.4020, 0.0967, 0.4354, 0.0276],
        [0.4570, 0.8452, 0.0613, 0.9891],
        [0.3939, 0.9505, 0.3234, 0.3256],
        [0.5124, 0.3632, 0.2360, 0.8110]])

ts_rand[:,1] = tensor([0.0967, 0.8452, 0.9505, 0.3632])


Concatenate or join

In [ ]:
# Concatenate or join
# Along the column
ts_ccat = torch.cat([ts_rand, torch.ones(4,4)], dim=1)
print(ts_ccat)

tensor([[0.4020, 0.0967, 0.4354, 0.0276, 1.0000, 1.0000, 1.0000, 1.0000],
        [0.4570, 0.8452, 0.0613, 0.9891, 1.0000, 1.0000, 1.0000, 1.0000],
        [0.3939, 0.9505, 0.3234, 0.3256, 1.0000, 1.0000, 1.0000, 1.0000],
        [0.5124, 0.3632, 0.2360, 0.8110, 1.0000, 1.0000, 1.0000, 1.0000]])


 Math operations

<font color='green'> Q2: Using multiplication operators with tensors ? </font>

In [ ]:
ts_res = ts_rand * ts_ccat
# What going on ?

RuntimeError: ignored

In [ ]:
ts_rand.matmul(ts_ccat)

tensor([[0.3914, 0.5445, 0.3283, 0.2709, 0.9617, 0.9617, 0.9617, 0.9617],
        [1.1009, 1.1761, 0.5040, 1.6708, 2.3526, 2.3526, 2.3526, 2.3526],
        [0.8869, 1.2672, 0.4111, 1.3204, 1.9934, 1.9934, 1.9934, 1.9934],
        [0.8805, 0.8754, 0.5130, 1.1079, 1.9226, 1.9226, 1.9226, 1.9226]])

Inplace operations

In [ ]:
ts_ccat.add_(5)

tensor([[5.4020, 5.0967, 5.4354, 5.0276, 6.0000, 6.0000, 6.0000, 6.0000],
        [5.4570, 5.8452, 5.0613, 5.9891, 6.0000, 6.0000, 6.0000, 6.0000],
        [5.3939, 5.9505, 5.3234, 5.3256, 6.0000, 6.0000, 6.0000, 6.0000],
        [5.5124, 5.3632, 5.2360, 5.8110, 6.0000, 6.0000, 6.0000, 6.0000]])

Tensors to Numpy ndrrays

In [ ]:
ts_x = torch.tensor([1,1,1])
arr_x = ts_x.numpy()
ts_x.add_(2)
print("Check if the value of the array has changed as well")
print(ts_x.numpy() == arr_x)

Check if the value of the array has changed as well
[ True  True  True]


<font color='light_blue'> In deep learning and with Pytorch, inputs and outputs as well as weights and biases are represented with tensors </font>

## 2- Learning Algorithm

Training a Neural Network happens in two steps:

*   **Forward Propagation**: It runs the input data through each layer and each activation of the network.
*   **Backward Propagation**: The NN adjusts its parameters proportionate to the error in its guess. Traversing backwards from the output, *collecting the derivatives of the error with respect to the parameters of the functions*, and optimizing the parameters using gradient descent.

More details [here](https://www.youtube.com/watch?v=tIeHLnjs5U8)



In [ ]:
from torch import nn 

class NN(nn.Module):
  def __init__(self):
    super().__init__()
    self.stack = nn.Sequential(
        nn.Linear(2,2),
        nn.Linear(2,1)
    )
  
  def forward(self, X):
    logits = self.stack(X)
    return logits

model = NN().to(device)
print(model)


NN(
  (stack): Sequential(
    (0): Linear(in_features=2, out_features=2, bias=True)
    (1): Linear(in_features=2, out_features=1, bias=True)
  )
)


In [ ]:
data = torch.tensor([[1,2],[3,4]], dtype=torch.float).to(device)
labels = torch.tensor([[0],[1]]).to(device)

#### **Forward Propagation**

In [ ]:
# Forward Pass
prediction = model(data)
print(f"The shape of the output tensor: {prediction.shape}")

The shape of the output tensor: torch.Size([2, 1])


#### **Prediction Errors - Loss**

In practice, most of the cases, we use predefined Loss functions

- MSELoss
- CrossEntropyLoss
- etc https://pytorch.org/docs/stable/nn.html


In [ ]:
# Calculate the loss, ie the error of the model given the prediction and the corresponding correct label
loss = (prediction - labels).sum()
print(f"Loss = {loss}")

Loss = -1.6862947940826416


#### **Backward Propagation - Autograd** 

In [ ]:
# Backpropagate the error through the network
# By calling backward on the error tensor, the Autograd will be triggered
# And the gradients for each model parameter are calculated and stored in the '.grad' attribute.
# In practice, we set all gradients to zero before calculating -- optimizer.zero_grad()
loss.backward()

#### **Optimizers**
Optimization Algorithms 

- Gradient Descent
- Stochastic Gradient Descent (SGD)
- Adam

Find more on:
https://pytorch.org/docs/stable/optim.html



In [ ]:
# Optimizer: register model parameters
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)
print("--------------------PARAMETERS----------------------")
print(f"Parameters before update: {list(model.parameters())}")
# Then finally initiate the gradient descent algorithm ( here the SGD) and updates all models parameters
# Set all gradients to zero before calculation
optimizer.zero_grad()
optimizer.step()
print("----------------------------------------------------")
print(f"Parameters after update: {list(model.parameters())}")

--------------------PARAMETERS----------------------
Parameters before update: [Parameter containing:
tensor([[ 0.0058, -0.0996],
        [ 0.4906, -0.1778]], device='cuda:0', requires_grad=True), Parameter containing:
tensor([ 0.4999, -0.4262], device='cuda:0', requires_grad=True), Parameter containing:
tensor([[-0.4108,  0.1036]], device='cuda:0', requires_grad=True), Parameter containing:
tensor([-0.2581], device='cuda:0', requires_grad=True)]
----------------------------------------------------
Parameters after update: [Parameter containing:
tensor([[ 0.0058, -0.0996],
        [ 0.4906, -0.1778]], device='cuda:0', requires_grad=True), Parameter containing:
tensor([ 0.4999, -0.4262], device='cuda:0', requires_grad=True), Parameter containing:
tensor([[-0.4108,  0.1036]], device='cuda:0', requires_grad=True), Parameter containing:
tensor([-0.2581], device='cuda:0', requires_grad=True)]


#### **Frozen Parameters**

In some cases, we don't need to update all parameters of the model, this is called **finetuning** in deep learning. To do so, we need to set the gradients to false for any parameters (Tensors) that are not required updates.

In [ ]:
for name, param in model.named_parameters():
  print(name)
  param.requires_grad_(False)

stack.0.weight
stack.0.bias
stack.1.weight
stack.1.bias


In [ ]:
model.get_parameter("stack.0.weight")

Parameter containing:
tensor([[ 0.3908, -0.0614],
        [-0.4358,  0.1849]], device='cuda:0')