<a href="https://colab.research.google.com/github/ManantenaKiady/Pytorch-fundamentals/blob/master/Notebooks/Pytorch_building_blocks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What you will learn

In this notebook, we will explore the building blocks of Pytorch ( Deep Learning)

- Tensors
- Learning Algorithms (Backpropagation)
  - Forward and Backward Pass
  - Auto-Grad
  - Optimizers
- Datasets
  - DataLoader

## Setup

In [2]:
!pip3 install torch torchvision torchaudio

# Check the installed version 
import torch
torch.__version__


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


'1.13.0+cu116'

Configure

In [3]:
# Check if GPU are available and set the device to use it
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

Using cuda device


## 1- Tensors

Tensors are a specialized data structure that are very similar to arrays and matrices. (Multidimentional Arrays)
 
*Source: https://pytorch.org/tutorials/*

eg of tensors: 

`scalar: 1`

`vector: [1, 2, 3]`

`matrices: [[1,2,3][4,5,6]]`

In [4]:
import torch

### Initialize Tensors with `torch`

**From Python list**

In [5]:
# List of list in Python 
m = [[1,2,3],[4,5,6]]
# Creating a tensor from list of list
M = torch.tensor(m)

print(f"Type of m: {type(m)}")
print(f"Type of M: {type(M)}")

Type of m: <class 'list'>
Type of M: <class 'torch.Tensor'>


**From Arrays (Numpy)**

What is numpy, who knows ?

Source: https://numpy.org/

In [6]:
import numpy as np 

# Convert m into numpy array
arr = np.array(m)
print(f"Type of arr: {type(arr)}")
# Transform arr into tensor
ts_arr = torch.tensor(arr)
print(f"Type of ts_arr: {type(ts_arr)}")

Type of arr: <class 'numpy.ndarray'>
Type of ts_arr: <class 'torch.Tensor'>


From another Tensor ?

**Tensor Attributes**

shape, dtype, device

<font color="green"> Q1: Create a tensor from a python list and print all attributes ? </font>

In [7]:
# ------- Write your answer here --------

To make a tensor use of a specific device, we can use the `to(device)` method.

In [8]:
ts_arr.device

device(type='cpu')

In [9]:
ts_arr = ts_arr.to(device)
print(f"Tensor ts_arr is stored on: {ts_arr.device}")

Tensor ts_arr is stored on: cuda:0


**Operations with Tensors**

Indexing, Slicing, Sampling, math Operations, etc More [here](https://pytorch.org/docs/stable/torch.html)

Indexing

In [10]:
# Indexing

ts_rand = torch.rand(4,4)
print(f"Tensor rand = {ts_rand}")
print()
# All rows of column 1
print(f"ts_rand[:,1] = {ts_rand[:,1]}")

Tensor rand = tensor([[0.1455, 0.2781, 0.0161, 0.9163],
        [0.1413, 0.3313, 0.9912, 0.8678],
        [0.9929, 0.1647, 0.0911, 0.5487],
        [0.8515, 0.5630, 0.7217, 0.9914]])

ts_rand[:,1] = tensor([0.2781, 0.3313, 0.1647, 0.5630])


Concatenate or join

In [11]:
# Concatenate or join
# Along the column
ts_ccat = torch.cat([ts_rand, torch.ones(4,4)], dim=1)
print(ts_ccat)

tensor([[0.1455, 0.2781, 0.0161, 0.9163, 1.0000, 1.0000, 1.0000, 1.0000],
        [0.1413, 0.3313, 0.9912, 0.8678, 1.0000, 1.0000, 1.0000, 1.0000],
        [0.9929, 0.1647, 0.0911, 0.5487, 1.0000, 1.0000, 1.0000, 1.0000],
        [0.8515, 0.5630, 0.7217, 0.9914, 1.0000, 1.0000, 1.0000, 1.0000]])


 Math operations

<font color='green'> Q2: Using multiplication operators with tensors ? </font>

In [12]:
ts_res = ts_rand * ts_ccat
# What going on ?

RuntimeError: ignored

In [13]:
ts_rand.matmul(ts_ccat)

tensor([[0.8567, 0.6511, 0.9408, 1.2919, 1.3560, 1.3560, 1.3560, 1.3560],
        [1.7905, 0.8009, 1.0473, 1.8211, 2.3316, 2.3316, 2.3316, 2.3316],
        [0.7254, 0.6546, 0.5836, 1.6467, 1.7974, 1.7974, 1.7974, 1.7974],
        [1.7642, 1.1003, 1.3530, 2.6476, 3.1276, 3.1276, 3.1276, 3.1276]])

Inplace operations

In [14]:
ts_ccat.add_(5)

tensor([[5.1455, 5.2781, 5.0161, 5.9163, 6.0000, 6.0000, 6.0000, 6.0000],
        [5.1413, 5.3313, 5.9912, 5.8678, 6.0000, 6.0000, 6.0000, 6.0000],
        [5.9929, 5.1647, 5.0911, 5.5487, 6.0000, 6.0000, 6.0000, 6.0000],
        [5.8515, 5.5630, 5.7217, 5.9914, 6.0000, 6.0000, 6.0000, 6.0000]])

Tensors to Numpy ndrrays

In [15]:
ts_x = torch.tensor([1,1,1])
arr_x = ts_x.numpy()
ts_x.add_(2)
print("Check if the value of the array has changed as well")
print(ts_x.numpy() == arr_x)

Check if the value of the array has changed as well
[ True  True  True]


<font color='light_blue'> In deep learning and with Pytorch, inputs and outputs as well as weights and biases are represented with tensors </font>

## 2- Learning Algorithm

Training a Neural Network happens in two steps:

*   **Forward Propagation**: It runs the input data through each layer and each activation of the network.
*   **Backward Propagation**: The NN adjusts its parameters proportionate to the error in its guess. Traversing backwards from the output, *collecting the derivatives of the error with respect to the parameters of the functions*, and optimizing the parameters using gradient descent.

More details [here](https://www.youtube.com/watch?v=tIeHLnjs5U8)



In [16]:
from torch import nn 

class NN(nn.Module):
  def __init__(self):
    super().__init__()
    self.stack = nn.Sequential(
        nn.Linear(2,2),
        nn.Linear(2,1)
    )
  
  def forward(self, X):
    logits = self.stack(X)
    return logits 

model = NN().to(device)
print(model)


NN(
  (stack): Sequential(
    (0): Linear(in_features=2, out_features=2, bias=True)
    (1): Linear(in_features=2, out_features=1, bias=True)
  )
)


In [17]:
data = torch.tensor([[1,2],[3,4]], dtype=torch.float).to(device)
labels = torch.tensor([[0],[1]]).to(device)

#### **Forward Propagation**

In [18]:
# Forward Pass
prediction = model(data)
print(f"The shape of the output tensor: {prediction.shape}")

The shape of the output tensor: torch.Size([2, 1])


#### **Prediction Errors**

In [19]:
# Calculate the loss, ie the error of the model given the prediction and the corresponding correct label
loss = (prediction - labels).sum()
print(f"Loss = {loss}")

Loss = 1.8394005298614502


### **Backward Propagation - Autograd** 

In [20]:
# Backpropagate the error through the network
# By calling backward on the error tensor, the Autograd will be triggered
# And the gradients for each model parameter are calculated and stored in the '.grad' attribute.
loss.backward()

#### **Optimizers**
Optimization Algorithms 

- Gradient Descent
- Stochastic Gradient Descent (SGD)
- Adam

Find more on:
https://pytorch.org/docs/stable/optim.html



In [23]:
# Optimizer: register model parameters
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)
print("--------------------PARAMETERS----------------------")
print(f"Parameters before update: {list(model.parameters())}")
# Then finally initiate the gradient descent algorithm ( here the SGD) and updates all models parameters
optimizer.step()
print("----------------------------------------------------")
print(f"Parameters after update: {list(model.parameters())}")

--------------------PARAMETERS----------------------
Parameters before update: [Parameter containing:
tensor([[-0.4758, -0.4409],
        [-0.0936,  0.1440]], device='cuda:0', requires_grad=True), Parameter containing:
tensor([ 0.4283, -0.4188], device='cuda:0', requires_grad=True), Parameter containing:
tensor([[-0.6365, -0.0831]], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.2303], device='cuda:0', requires_grad=True)]
----------------------------------------------------
Parameters after update: [Parameter containing:
tensor([[-0.4732, -0.4371],
        [-0.0932,  0.1445]], device='cuda:0', requires_grad=True), Parameter containing:
tensor([ 0.4295, -0.4186], device='cuda:0', requires_grad=True), Parameter containing:
tensor([[-0.6328, -0.0827]], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.2283], device='cuda:0', requires_grad=True)]


**Frozen Parameters**

In some cases, we don't need to update all parameters of the model, this is called **finetuning** in deep learning. To do so, we need to set the gradients to false for any parameters (Tensors) that are not required updates.

In [24]:
for name, param in model.named_parameters():
  print(name)
  param.requires_grad_(False)

stack.0.weight
stack.0.bias
stack.1.weight
stack.1.bias


In [25]:
model.get_parameter("stack.0.weight")

Parameter containing:
tensor([[-0.4732, -0.4371],
        [-0.0932,  0.1445]], device='cuda:0')