<a href="https://colab.research.google.com/github/ManantenaKiady/Pytorch-fundamentals/blob/master/Notebooks/Pytorch_building_blocks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What you will learn

In this notebook, we will explore the building blocks of Pytorch ( Deep Learning)

- Tensors
- Learning Algorithms (Backpropagation)
  - Forward and Backward Pass
  - Auto-Grad
- Datasets
  - DataLoader
- Optimizers

## Setup

In [1]:
!pip3 install torch torchvision torchaudio

# Check the installed version 
import torch
torch.__version__


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


'1.13.0+cu116'

Configure

In [2]:
# Check if GPU are available and set the device to use it
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

Using cuda device


## 1- Tensors

Tensors are a specialized data structure that are very similar to arrays and matrices. (Multidimentional Arrays)
 
*Source: https://pytorch.org/tutorials/*

eg of tensors: 

`scalar: 1`

`vector: [1, 2, 3]`

`matrices: [[1,2,3][4,5,6]]`

In [3]:
import torch

### Initialize Tensors with `torch`

**From Python list**

In [4]:
# List of list in Python 
m = [[1,2,3],[4,5,6]]
# Creating a tensor from list of list
M = torch.tensor(m)

print(f"Type of m: {type(m)}")
print(f"Type of M: {type(M)}")

Type of m: <class 'list'>
Type of M: <class 'torch.Tensor'>


**From Arrays (Numpy)**

What is numpy, who knows ?

Source: https://numpy.org/

In [5]:
import numpy as np 

# Convert m into numpy array
arr = np.array(m)
print(f"Type of arr: {type(arr)}")
# Transform arr into tensor
ts_arr = torch.tensor(arr)
print(f"Type of ts_arr: {type(ts_arr)}")

Type of arr: <class 'numpy.ndarray'>
Type of ts_arr: <class 'torch.Tensor'>


From another Tensor ?

**Tensor Attributes**

shape, dtype, device

<font color="green"> Q1: Create a tensor from a python list and print all attributes ? </font>

In [6]:
# ------- Write your answer here --------

To make a tensor use of a specific device, we can use the `to(device)` method.

In [7]:
ts_arr.device

device(type='cpu')

In [8]:
ts_arr = ts_arr.to(device)
print(f"Tensor ts_arr is stored on: {ts_arr.device}")

Tensor ts_arr is stored on: cuda:0


**Operations with Tensors**

Indexing, Slicing, Sampling, math Operations, etc More [here](https://pytorch.org/docs/stable/torch.html)

Indexing

In [9]:
# Indexing

ts_rand = torch.rand(4,4)
print(f"Tensor rand = {ts_rand}")
print()
# All rows of column 1
print(f"ts_rand[:,1] = {ts_rand[:,1]}")

Tensor rand = tensor([[0.8296, 0.3214, 0.8495, 0.0197],
        [0.2561, 0.9025, 0.0454, 0.8535],
        [0.4532, 0.2181, 0.1884, 0.8337],
        [0.2751, 0.0222, 0.5432, 0.1372]])

ts_rand[:,1] = tensor([0.3214, 0.9025, 0.2181, 0.0222])


Concatenate or join

In [10]:
# Concatenate or join
# Along the column
ts_ccat = torch.cat([ts_rand, torch.ones(4,4)], dim=1)
print(ts_ccat)

tensor([[0.8296, 0.3214, 0.8495, 0.0197, 1.0000, 1.0000, 1.0000, 1.0000],
        [0.2561, 0.9025, 0.0454, 0.8535, 1.0000, 1.0000, 1.0000, 1.0000],
        [0.4532, 0.2181, 0.1884, 0.8337, 1.0000, 1.0000, 1.0000, 1.0000],
        [0.2751, 0.0222, 0.5432, 0.1372, 1.0000, 1.0000, 1.0000, 1.0000]])


 Math operations

<font color='green'> Q2: Using multiplication operators with tensors ? </font>

In [19]:
ts_res = ts_rand * ts_ccat
# What going on ?

RuntimeError: ignored

In [12]:
ts_rand.matmul(ts_ccat)

tensor([[1.1609, 0.7424, 0.8900, 1.0015, 2.0201, 2.0201, 2.0201, 2.0201],
        [0.6989, 0.9256, 0.7307, 0.9303, 2.0575, 2.0575, 2.0575, 2.0575],
        [0.7465, 0.4021, 0.8832, 0.4666, 1.6934, 1.6934, 1.6934, 1.6934],
        [0.5178, 0.2300, 0.4116, 0.4961, 0.9777, 0.9777, 0.9777, 0.9777]])

Inplace operations

In [13]:
ts_ccat.add_(5)

tensor([[5.8296, 5.3214, 5.8495, 5.0197, 6.0000, 6.0000, 6.0000, 6.0000],
        [5.2561, 5.9025, 5.0454, 5.8535, 6.0000, 6.0000, 6.0000, 6.0000],
        [5.4532, 5.2181, 5.1884, 5.8337, 6.0000, 6.0000, 6.0000, 6.0000],
        [5.2751, 5.0222, 5.5432, 5.1372, 6.0000, 6.0000, 6.0000, 6.0000]])

Tensors to Numpy ndrrays

In [18]:
ts_x = torch.tensor([1,1,1])
arr_x = ts_x.numpy()
ts_x.add_(2)
print("Check if the value of the array has changed as well")
print(ts_x.numpy() == arr_x)

Check if the value of the array has changed as well
[ True  True  True]


<font color='light_blue'> In deep learning and with Pytorch, inputs and outputs as well as weights and biases are represented with tensors </font>

## 2- Learning Algorithm

Training a Neural Network happens in two steps:

*   **Forward Propagation**: It runs the input data through each layer and each activation of the network.
*   **Backward Propagation**: The NN adjusts its parameters proportionate to the error in its guess. Traversing backwards from the output, *collecting the derivatives of the error with respect to the parameters of the functions*, and optimizing the parameters using gradient descent.

More details [here](https://www.youtube.com/watch?v=tIeHLnjs5U8)



In [20]:
from torchvision.models import resnet18, ResNet18_Weights
model = resnet18(weights=ResNet18_Weights.DEFAULT)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth


  0%|          | 0.00/44.7M [00:00<?, ?B/s]

In [28]:
# Forward Pass
prediction = model(data)
print(f"The shape of the output tensor: {prediction.shape}")

# Calculate the loss, ie the error of the model given the prediction and the corresponding correct label
loss = (prediction - labels).sum()
print(f"Loss = {loss}")

# Backpropagate the error through the network
# By calling backward on the error tensor, the Autograd will be triggered
# And the gradients for each model parameter are calculated and stored in the '.grad' attribute.
loss.backward()


The shape of the output tensor: torch.Size([1, 1000])
Loss = -517.5660400390625


In [33]:
loss.grad

<ipython-input-33-09a6243c8d35>:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:480.)
  loss.grad
