<a href="https://colab.research.google.com/github/ManantenaKiady/Pytorch-fundamentals/blob/master/Notebooks/Pytorch_building_blocks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What you will learn

In this notebook, we will explore the building blocks of Pytorch ( Deep Learning)

- Tensors
- Learning Algorithms (Backpropagation)
  - Forward and Backward Pass
  - Auto-Grad
- Datasets
  - DataLoader
- Optimizers

## Setup

In [3]:
!pip3 install torch torchvision torchaudio

# Check the installed version 
import torch
torch.__version__


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


'1.13.0+cu116'

Configure

In [4]:
# Check if GPU are available and set the device to use it
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

Using cuda device


## 1- Tensors

Tensors are a specialized data structure that are very similar to arrays and matrices. (Multidimentional Arrays)
 
*Source: https://pytorch.org/tutorials/*

eg of tensors: 

`scalar: 1`

`vector: [1, 2, 3]`

`matrices: [[1,2,3][4,5,6]]`

In [5]:
import torch

### Initialize Tensors with `torch`

**From Python list**

In [6]:
# List of list in Python 
m = [[1,2,3],[4,5,6]]
# Creating a tensor from list of list
M = torch.tensor(m)

print(f"Type of m: {type(m)}")
print(f"Type of M: {type(M)}")

Type of m: <class 'list'>
Type of M: <class 'torch.Tensor'>


**From Arrays (Numpy)**

What is numpy, who knows ?

Source: https://numpy.org/

In [7]:
import numpy as np 

# Convert m into numpy array
arr = np.array(m)
print(f"Type of arr: {type(arr)}")
# Transform arr into tensor
ts_arr = torch.tensor(arr)
print(f"Type of ts_arr: {type(ts_arr)}")

Type of arr: <class 'numpy.ndarray'>
Type of ts_arr: <class 'torch.Tensor'>


From another Tensor ?

**Tensor Attributes**

shape, dtype, device

<font color="green"> Q1: Create a tensor from a python list and print all attributes ? </font>

In [8]:
# ------- Write your answer here --------

To make a tensor use of a specific device, we can use the `to(device)` method.

In [9]:
ts_arr.device

device(type='cpu')

In [10]:
ts_arr = ts_arr.to(device)
print(f"Tensor ts_arr is stored on: {ts_arr.device}")

Tensor ts_arr is stored on: cuda:0


**Operations with Tensors**

Indexing, Slicing, Sampling, math Operations, etc More [here](https://pytorch.org/docs/stable/torch.html)

Indexing

In [11]:
# Indexing

ts_rand = torch.rand(4,4)
print(f"Tensor rand = {ts_rand}")
print()
# All rows of column 1
print(f"ts_rand[:,1] = {ts_rand[:,1]}")

Tensor rand = tensor([[0.8772, 0.9894, 0.9061, 0.3360],
        [0.4406, 0.2018, 0.6038, 0.4859],
        [0.0596, 0.0577, 0.9347, 0.0448],
        [0.4305, 0.2725, 0.3176, 0.8522]])

ts_rand[:,1] = tensor([0.9894, 0.2018, 0.0577, 0.2725])


Concatenate or join

In [12]:
# Concatenate or join
# Along the column
ts_ccat = torch.cat([ts_rand, torch.ones(4,4)], dim=1)
print(ts_ccat)

tensor([[0.8772, 0.9894, 0.9061, 0.3360, 1.0000, 1.0000, 1.0000, 1.0000],
        [0.4406, 0.2018, 0.6038, 0.4859, 1.0000, 1.0000, 1.0000, 1.0000],
        [0.0596, 0.0577, 0.9347, 0.0448, 1.0000, 1.0000, 1.0000, 1.0000],
        [0.4305, 0.2725, 0.3176, 0.8522, 1.0000, 1.0000, 1.0000, 1.0000]])


 Math operations

<font color='green'> Q2: Using multiplication operators with tensors ? </font>

In [13]:
ts_res = ts_rand * ts_ccat
# What going on ?

RuntimeError: ignored

In [14]:
ts_rand.matmul(ts_ccat)

tensor([[1.4042, 1.2114, 2.3459, 1.1024, 3.1087, 3.1087, 3.1087, 3.1087],
        [0.7207, 0.6439, 1.2398, 0.6873, 1.7321, 1.7321, 1.7321, 1.7321],
        [0.1528, 0.1368, 0.9767, 0.1281, 1.0968, 1.0968, 1.0968, 1.0968],
        [0.8836, 0.7315, 1.1221, 1.0176, 1.8728, 1.8728, 1.8728, 1.8728]])

Inplace operations

In [15]:
ts_ccat.add_(5)

tensor([[5.8772, 5.9894, 5.9061, 5.3360, 6.0000, 6.0000, 6.0000, 6.0000],
        [5.4406, 5.2018, 5.6038, 5.4859, 6.0000, 6.0000, 6.0000, 6.0000],
        [5.0596, 5.0577, 5.9347, 5.0448, 6.0000, 6.0000, 6.0000, 6.0000],
        [5.4305, 5.2725, 5.3176, 5.8522, 6.0000, 6.0000, 6.0000, 6.0000]])

Tensors to Numpy ndrrays

In [16]:
ts_x = torch.tensor([1,1,1])
arr_x = ts_x.numpy()
ts_x.add_(2)
print("Check if the value of the array has changed as well")
print(ts_x.numpy() == arr_x)

Check if the value of the array has changed as well
[ True  True  True]


<font color='light_blue'> In deep learning and with Pytorch, inputs and outputs as well as weights and biases are represented with tensors </font>

## 2- Learning Algorithm

Training a Neural Network happens in two steps:

*   **Forward Propagation**: It runs the input data through each layer and each activation of the network.
*   **Backward Propagation**: The NN adjusts its parameters proportionate to the error in its guess. Traversing backwards from the output, *collecting the derivatives of the error with respect to the parameters of the functions*, and optimizing the parameters using gradient descent.

More details [here](https://www.youtube.com/watch?v=tIeHLnjs5U8)



In [60]:
from torch import nn 

class NN(nn.Module):
  def __init__(self):
    super().__init__()
    self.stack = nn.Sequential(
        nn.Linear(2,2),
        nn.Linear(2,1)
    )
  
  def forward(self, X):
    logits = self.stack(X)
    return logits 

model = NN().to(device)
print(model)


NN(
  (stack): Sequential(
    (0): Linear(in_features=2, out_features=2, bias=True)
    (1): Linear(in_features=2, out_features=1, bias=True)
  )
)


In [61]:
data = torch.tensor([[1,2],[3,4]], dtype=torch.float).to(device)
labels = torch.tensor([[0],[1]]).to(device)

In [65]:
# Forward Pass
prediction = model(data)
print(f"The shape of the output tensor: {prediction.shape}")

# Calculate the loss, ie the error of the model given the prediction and the corresponding correct label
loss = (prediction - labels).sum()
print(f"Loss = {loss}")

# Backpropagate the error through the network
# By calling backward on the error tensor, the Autograd will be triggered
# And the gradients for each model parameter are calculated and stored in the '.grad' attribute.
loss.backward()

# Optimizer: create and register model parameters
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)
print("--------------------PARAMETERS----------------------")
print(f"Parameters before update: {list(model.parameters())}")
# Then finally initiate the gradient descent algorithm ( here the SGD) and updates all models parameters
optimizer.step()
print("----------------------------------------------------")
print(f"Parameters after update: {list(model.parameters())}")

The shape of the output tensor: torch.Size([2, 1])
Loss = -1.3901338577270508
--------------------PARAMETERS----------------------
Parameters before update: [Parameter containing:
tensor([[ 0.3225, -0.0558],
        [ 0.2485,  0.0699]], device='cuda:0', requires_grad=True), Parameter containing:
tensor([-0.0340, -0.2507], device='cuda:0', requires_grad=True), Parameter containing:
tensor([[-0.3925, -0.3121]], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.1215], device='cuda:0', requires_grad=True)]
----------------------------------------------------
Parameters after update: [Parameter containing:
tensor([[ 0.3288, -0.0464],
        [ 0.2535,  0.0773]], device='cuda:0', requires_grad=True), Parameter containing:
tensor([-0.0309, -0.2482], device='cuda:0', requires_grad=True), Parameter containing:
tensor([[-0.3958, -0.3155]], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.1135], device='cuda:0', requires_grad=True)]


**Frozen Parameters**

In some cases, we don't need to update all parameters of the model, this is called **finetuning** in deep learning. To do so, we need to set the gradients to false for any parameters (Tensors) that are not required updates.

In [70]:
for name, param in model.named_parameters():
  print(name)
  param.requires_grad_(False)

stack.0.weight
stack.0.bias
stack.1.weight
stack.1.bias


In [76]:
model.get_parameter("stack.0.weight")

Parameter containing:
tensor([[ 0.3288, -0.0464],
        [ 0.2535,  0.0773]], device='cuda:0')